var x5CartData = {
	// General Cart Settings
	'settings': {
		'indexpage': 'cart/index.html',
		'loginpage': '',
		'continue_shopping_page': 'https://www.rossipizza.eu/index.html',
		'vat': 0.2,
		'vattype': 'included', // included|excluded|none
		'currency': 'лв',
		'currency_id': 'BGN',
		'showShipmentFields': false,
		'cartCookie': 'x5CartProductstvy0wi529f34111o',
		'formCookie': 'x5CartFormtvy0wi529f34111o',
		'registerUsers': false,
		'currency_format': '#.###,@@ [C]',
		'currency_format_zeroas': '0',
		'order_no_format': '[yy][mm][dd]-[A-Z][A-Z][0-9][0-9]',
		'formAutocomplete': true,
		'formValidation': 'tip',
		'remove_from_cart_icon': 'cart/images/cart-remove.png',
		'add_to_cart_icon': 'cart/images/cart-add.png',
		'minimumAmount': 0,
		'currencies': [{ "value": "ALL", "text": "Albania, Leke, Lek" }, { "value": "USD", "text": "United States of America, Dollars, $" }, { "value": "AFN", "text": "Afghanistan, Afghanis, ؋" }, { "value": "ARS", "text": "Argentina, Pesos, $" }, { "value": "AUD", "text": "Australia, Dollars, $" }, { "value": "BGN", "text": "Bulgarian, Lev, лв" }, { "value": "BRL", "text": "Brazil, Reais, R$" }, { "value": "GBP", "text": "United Kingdom, Pounds, £" }, { "value": "BND", "text": "Brunei Darussalam, Dollars, $" }, { "value": "CAD", "text": "Canada, Dollars, $" }, { "value": "CNY", "text": "China, Yuan Renminbi, ¥" }, { "value": "HRK", "text": "Croatia, Kuna, ₡" }, { "value": "CZK", "text": "Czech Republic, Koruny, Kč" }, { "value": "DKK", "text": "Denmark, Kroner, kr" }, { "value": "EGP", "text": "Egypt, Pounds, £" }, { "value": "EUR", "text": "Euro, €" }, { "value": "GTQ", "text": "Guatemala, Quetzales, Q" }, { "value": "HKD", "text": "Hong Kong, Dollars, $" }, { "value": "HUF", "text": "Hungary, Forint, Ft" }, { "value": "ISK", "text": "Iceland, Kronur, kr" }, { "value": "INR", "text": "India, Rupees, Rs" }, { "value": "IDR", "text": "Indonesia, Rupiahs, Rp" }, { "value": "IRR", "text": "Iran, Rials, ﷼" }, { "value": "ILS", "text": "Israel, New Shekels, ₪" }, { "value": "JPY", "text": "Japan, Yen, ¥" }, { "value": "KZT", "text": "Kazakhstan, Tenge, тг" }, { "value": "KPW", "text": "Korea (North), Won, ₩" }, { "value": "KRW", "text": "Korea (South), Won, ₩" }, { "value": "LVL", "text": "Latvia, Lati, Ls" }, { "value": "LTL", "text": "Lithuania, Litai, Lt" }, { "value": "MYR", "text": "Malaysia, Ringgits, RM" }, { "value": "MXN", "text": "Mexico, Pesos, $" }, { "value": "NZD", "text": "New Zealand, Dollars, $" }, { "value": "NOK", "text": "Norway, Kroner, kr" }, { "value": "OMR", "text": "Oman, Rials, ﷼" }, { "value": "PLN", "text": "Poland, Zlotych, zł" }, { "value": "QAR", "text": "Qatar, Rials, ﷼" }, { "value": "RON", "text": "Romania, New Lei, lei" }, { "value": "RUB", "text": "Russia, Rubles, руб" }, { "value": "SAR", "text": "Saudi Arabia, Riyals, ﷼" }, { "value": "RSD", "text": "Serbia, Dinars, Дин." }, { "value": "SGD", "text": "Singapore, Dollars, $" }, { "value": "ZAR", "text": "South Africa, Rand, R" }, { "value": "SEK", "text": "Sweden, Kronor, kr" }, { "value": "CHF", "text": "Switzerland, Francs, CHF" }, { "value": "TWD", "text": "Taiwan, New Dollars, NT$" }, { "value": "THB", "text": "Thailand, Baht, ฿" }, { "value": "TTD", "text": "Trinidad and Tobago, Dollars, TT$" }, { "value": "TRY", "text": "Turkey, Lira, ₺" }, { "value": "UAH", "text": "Ukraine, Hryvnia, ₴" }]
	},

	// Cart Products
	'products': {
		'2dzsnahu': {
			'id': '2dzsnahu',
			'id_user': 'Спанак с киноа /1, 6, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Спанак с киноа /1, 6, 7, 8/',
			'category': '91vhzmwe',
			'description': '/спанак, киноа, сирене, домати, яйце, печ. чушки, сос/ ..... 380 гр.',
			'price': 7.325,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.38
		},
		'1pwd5iz4': {
			'id': '1pwd5iz4',
			'id_user': 'Дорина /7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Дорина /7/',
			'category': '91vhzmwe',
			'description': '/сушени домати, салата - 2 вида, пармезан, гъби, чери домати/ ..... 400 гр.',
			'price': 8.075,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.4
		},
		'd4ia7i4s': {
			'id': 'd4ia7i4s',
			'id_user': 'Миланзана /7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Миланзана /7/',
			'category': '91vhzmwe',
			'description': '/патладжан, печени чушки, домат, сирене, магданоз, дресинг/ ..... 350 гр.',
			'price': 8.075,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.35
		},
		'rdq0fopk': {
			'id': 'rdq0fopk',
			'id_user': 'Цезар /1, 5, 6, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Цезар /1, 5, 6, 7, 8/',
			'category': '91vhzmwe',
			'description': '/айсберг, крутони, пиле, пармезан, сос цезар, балсамова редукция/ ..... 300 гр.',
			'price': 8.075,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'y2gkzepp': {
			'id': 'y2gkzepp',
			'id_user': 'Айсберг /6, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Айсберг /6, 7, 8/',
			'category': '91vhzmwe',
			'description': '/айсберг, пил. месо, кис. краставички, маслини, яйце, чери домати, пармезан, сос/ ..... 350 гр.',
			'price': 8.075,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.35
		},
		'3x3gf4tq': {
			'id': '3x3gf4tq',
			'id_user': 'Шопска /7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Шопска /7/',
			'category': '91vhzmwe',
			'description': '/домати, краставици, лук, печ. чушки, сирене, магданоз/ ..... 400 гр.',
			'price': 6.6583333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.4
		},
		'j8qezb36': {
			'id': 'j8qezb36',
			'id_user': 'Гръцка /7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Гръцка /7/',
			'category': '91vhzmwe',
			'description': '/домати, краставици, сирене, маслини, лук, риган/ ..... 500 гр.',
			'price': 8.075,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.5
		},
		'8vy39o7h': {
			'id': '8vy39o7h',
			'id_user': 'Радиче / 4, 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Радиче / 4, 7/',
			'category': '91vhzmwe',
			'description': '/козе сирене, салата - 2 вида, бадеми, сладки от боровинки, чери домати, стафиди, балсамова редукция/ ..... 350 гр.',
			'price': 9.9916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.35
		},
		'rh28zt40': {
			'id': 'rh28zt40',
			'id_user': 'Броколи /6, 7, 9/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Броколи /6, 7, 9/',
			'category': '91vhzmwe',
			'description': '/броколи, айце, сусам, дресинг/ ..... 300 гр.',
			'price': 7.2416667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.3
		},
		'ebx5ws6w': {
			'id': 'ebx5ws6w',
			'id_user': 'Зелена салата /6/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Зелена салата /6/',
			'category': '91vhzmwe',
			'description': '/маруля, репички, пр. лук, краставици, яйце/ ..... 350 гр.',
			'price': 6.4083333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.35
		},
		'324trsgq': {
			'id': '324trsgq',
			'id_user': 'Капрезе с моцарела /7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Капрезе с моцарела /7/',
			'category': '91vhzmwe',
			'description': '/домати, зехтин, босилек, моцарела/ ..... 440 гр.',
			'price': 8.075,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.44
		},
		'eqtw4ogk': {
			'id': 'eqtw4ogk',
			'id_user': 'Салата "Авокадо" /7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Салата "Авокадо" /7/',
			'category': '91vhzmwe',
			'description': '/айсберг, рукола, сушени домати, краставица, авокадо, дресинг/ ..... 350 гр.',
			'price': 9.1583333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.35
		},
		'd7los9u6': {
			'id': 'd7los9u6',
			'id_user': 'Зеленчукови кюфтенца /млечен сон/6, 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Зеленчукови кюфтенца /млечен сон/6, 7/',
			'category': 'knd7d7sr',
			'description': '200 гр.',
			'price': 6.2416667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 1.2
		},
		'4g3x21ed': {
			'id': '4g3x21ed',
			'id_user': 'Топли сол. палачинки с шунка - 1 бр.',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Топли сол. палачинки с шунка - 1 бр.',
			'category': 'knd7d7sr',
			'description': '/шунка, кис. краставички, кашкавал, сирене, топ. сирене, сметана/',
			'price': 3.9083333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'xo6apsm0': {
			'id': 'xo6apsm0',
			'id_user': 'Топли солени палачинки - 2 бр. /1, 6, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Топли солени палачинки - 2 бр. /1, 6, 7, 8/',
			'category': 'knd7d7sr',
			'description': '/шунка, кис. краставички, кашкавал, сирене, топ. сирене, сметана/',
			'price': 7.075,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'35uout59': {
			'id': '35uout59',
			'id_user': 'Топли сол. палачинки със сирене - 1 бр.',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Топли сол. палачинки със сирене - 1 бр.',
			'category': 'knd7d7sr',
			'description': '/сирене, топ. сирене, царевица, сметана, подправки/',
			'price': 3.9083333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'5ztv5b3h': {
			'id': '5ztv5b3h',
			'id_user': 'Топли сол. палачинки със сирене - 2 бр.',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Топли сол. палачинки със сирене - 2 бр.',
			'category': 'knd7d7sr',
			'description': 'сирене, топ. сирене, царевица, сметана, подправки',
			'price': 6.4083333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'q0t69pzd': {
			'id': 'q0t69pzd',
			'id_user': 'Панирани броколи /млечен сос/1, 6/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Панирани броколи /млечен сос/1, 6/',
			'category': 'knd7d7sr',
			'description': '300 гр.',
			'price': 6.2416667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.3
		},
		'4hyqcvm7': {
			'id': '4hyqcvm7',
			'id_user': 'Панирани сиренца',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Панирани сиренца',
			'category': 'knd7d7sr',
			'description': '200 гр.',
			'price': 3.825,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'zvrdg5tg': {
			'id': 'zvrdg5tg',
			'id_user': 'Панирани кашкавалчета',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Панирани кашкавалчета',
			'category': 'knd7d7sr',
			'description': '200 гр.',
			'price': 5.825,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'hlpnq8hi': {
			'id': 'hlpnq8hi',
			'id_user': 'Панирани топени сиренца /1, 6, 7, 10/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Панирани топени сиренца /1, 6, 7, 10/',
			'category': 'knd7d7sr',
			'description': '/топени сиренца, сусам, сладко от боровинки/ ..... 200 гр.',
			'price': 6.075,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.2
		},
		'j18hw3yj': {
			'id': 'j18hw3yj',
			'id_user': 'Кюфтенца от киноа /1, 6/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Кюфтенца от киноа /1, 6/',
			'category': 'knd7d7sr',
			'description': '/киноа, суш. домати, маслини, пресен лук, магданоз, чесън, подправки/ ..... 250 гр,',
			'price': 6.4083333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.25
		},
		'z23xt914': {
			'id': 'z23xt914',
			'id_user': 'Тиквички по гръцки с млечен сос /1/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Тиквички по гръцки с млечен сос /1/',
			'category': 'knd7d7sr',
			'description': '300 гр.',
			'price': 7.2416667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.3
		},
		'tsr44cfa': {
			'id': 'tsr44cfa',
			'id_user': 'Пилешки дробчета /1, 5, 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Пилешки дробчета /1, 5, 7/',
			'category': '5lezw5li',
			'description': '/със специален сос, магданоз, кис. краставички/ ..... 350 гр.',
			'price': 6.9916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.35
		},
		'cv5vr58a': {
			'id': 'cv5vr58a',
			'id_user': 'Пилешки крилца',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Пилешки крилца',
			'category': '5lezw5li',
			'description': '/запеч. мариновани крилца/ ..... 550 гр.',
			'price': 6.9916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.55
		},
		'xn7bkxol': {
			'id': 'xn7bkxol',
			'id_user': 'Пилешки филенца /1, 6, 8, 10/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Пилешки филенца /1, 6, 8, 10/',
			'category': '5lezw5li',
			'description': '/с корнфлейкс и сос/ ..... 300 гр.',
			'price': 8.075,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.3
		},
		'funs59f8': {
			'id': 'funs59f8',
			'id_user': 'Пиле Полар /7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Пиле Полар /7, 8/',
			'category': '5lezw5li',
			'description': '/пил. филе, пушено сирене, синьо сирене, сметана/ ..... 350 гр.',
			'price': 8.075,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.35
		},
		'f99vn2wm': {
			'id': 'f99vn2wm',
			'id_user': 'С шунка /7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'С шунка /7, 8/',
			'category': 'hi0dxewt',
			'description': '/картофи, шунка, сметана, кашкавал, лук, масло, магданоз/ ..... 400 гр.',
			'price': 6.9916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.4
		},
		'nsjk9qv0': {
			'id': 'nsjk9qv0',
			'id_user': 'С пушено пиле /1, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'С пушено пиле /1, 7, 8/',
			'category': 'hi0dxewt',
			'description': '/картофи, пуш. пиле, масло, лук, дом. сос, кашкавал, копър/ ..... 400 гр.',
			'price': 6.9916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.4
		},
		'f0co9rsm': {
			'id': 'f0co9rsm',
			'id_user': 'Фло /7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Фло /7, 8/',
			'category': 'hi0dxewt',
			'description': '/броколи, сметана, шунка, кашкавал, рокфор, подправки/ ..... 400 гр.',
			'price': 7.4916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.4
		},
		'ow6muzrt': {
			'id': 'ow6muzrt',
			'id_user': 'Картофи соте',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Картофи соте',
			'category': 'po6sws6r',
			'description': '300 гр.',
			'price': 3.075,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'znq8r52c': {
			'id': 'znq8r52c',
			'id_user': 'Пържени картофи',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Пържени картофи',
			'category': 'po6sws6r',
			'description': '300 гр.',
			'price': 3.825,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.3
		},
		'gu31l52p': {
			'id': 'gu31l52p',
			'id_user': 'Пикантни картофи',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Пикантни картофи',
			'category': 'po6sws6r',
			'description': '250 гр.',
			'price': 3.9083333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'jolw20yz': {
			'id': 'jolw20yz',
			'id_user': 'Пържени картофи със сирене',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Пържени картофи със сирене',
			'category': 'po6sws6r',
			'description': '350 гр.',
			'price': 3.825,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'nvpu2gw9': {
			'id': 'nvpu2gw9',
			'id_user': 'По Тексаски или Мариновани',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'По Тексаски или Мариновани',
			'category': 'awgkf0ry',
			'description': '500 гр.',
			'price': 9.075,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'esbojx8y': {
			'id': 'esbojx8y',
			'id_user': 'Кюфтенца /сос Барбекю/ 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Кюфтенца /сос Барбекю/ 8/',
			'category': 'zucwh6z4',
			'description': '240 гр.',
			'price': 5.4083333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.24
		},
		'6n1o7z4u': {
			'id': '6n1o7z4u',
			'id_user': 'Свинска вратна пържола',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Свинска вратна пържола',
			'category': 'zucwh6z4',
			'description': '300 гр.',
			'price': 7.6583333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.3
		},
		'tb1g8e8q': {
			'id': 'tb1g8e8q',
			'id_user': 'Свинско шишче',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Свинско шишче',
			'category': 'zucwh6z4',
			'description': '120 гр.',
			'price': 2.825,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'ydlkougg': {
			'id': 'ydlkougg',
			'id_user': 'Пилешка пържола /8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Пилешка пържола /8/',
			'category': 'zucwh6z4',
			'description': '250 гр.',
			'price': 6.6583333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.25
		},
		'vkf957q8': {
			'id': 'vkf957q8',
			'id_user': 'Пилешко шишче',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Пилешко шишче',
			'category': 'zucwh6z4',
			'description': '100 гр.',
			'price': 2.2416667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'jlq5bo9c': {
			'id': 'jlq5bo9c',
			'id_user': 'Зеленчуци на скара',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Зеленчуци на скара',
			'category': 'zucwh6z4',
			'description': '400 гр.',
			'price': 5.825,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.4
		},
		'40wv5axd': {
			'id': '40wv5axd',
			'id_user': 'Таратор /7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Таратор /7/',
			'category': 'k7qxcsrm',
			'description': '400 гр.',
			'price': 2.6583333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.04
		},
		'zbtthm0x': {
			'id': 'zbtthm0x',
			'id_user': 'Пилешка супа /7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Пилешка супа /7, 8/',
			'category': 'k7qxcsrm',
			'description': '400 гр.',
			'price': 3.4916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.4
		},
		'yx2le9oa': {
			'id': 'yx2le9oa',
			'id_user': 'Картофена крем супа /1, 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Картофена крем супа /1, 7/',
			'category': 'k7qxcsrm',
			'description': '400 гр.',
			'price': 3.4916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.4
		},
		'6lege1jg': {
			'id': '6lege1jg',
			'id_user': 'Бисквитена торта /1, 4, 7, 8.',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Бисквитена торта /1, 4, 7, 8.',
			'category': '87djswgg',
			'description': '180 гр.',
			'price': 4.075,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.18
		},
		'voct5y2u': {
			'id': 'voct5y2u',
			'id_user': 'Крем "Брюле" /1, 6, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Крем "Брюле" /1, 6, 7, 8/',
			'category': '87djswgg',
			'description': '/с чия/ ..... 150 гр.',
			'price': 3.325,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.15
		},
		'p7qoz7u5': {
			'id': 'p7qoz7u5',
			'id_user': 'Торта ала Гараш /4, 6, 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Торта ала Гараш /4, 6, 7/',
			'category': '87djswgg',
			'description': '100 гр.',
			'price': 5.2416667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.1
		},
		'vad2v3me': {
			'id': 'vad2v3me',
			'id_user': 'Палачинка - 1 бр.',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Палачинка - 1 бр.',
			'category': '87djswgg',
			'description': '/с шоколад, сладко по избор/',
			'price': 2.575,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'bjgsiyun': {
			'id': 'bjgsiyun',
			'id_user': 'Крем "Луи XIV" /4, 5, 6, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Крем "Луи XIV" /4, 5, 6, 8/',
			'category': '87djswgg',
			'description': '100 гр.',
			'price': 4.825,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.1
		},
		'olsflim9': {
			'id': 'olsflim9',
			'id_user': 'Тирамису /1, 6, 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Тирамису /1, 6, 7/',
			'category': '87djswgg',
			'description': '150 гр.',
			'price': 4.825,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.15
		},
		'5yjoewzc': {
			'id': '5yjoewzc',
			'id_user': 'Маргарита /1, 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Маргарита /1, 7/',
			'category': 'zt5zv3xr',
			'description': '/дом. сос, кашкавал, босилек/',
			'price': 7.4916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'nnfg21px': {
			'id': 'nnfg21px',
			'id_user': 'Коща /1, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Коща /1, 7, 8/',
			'category': 'zt5zv3xr',
			'description': '/дом. сос, кашкавал, шунка, гъби/',
			'price': 8.6583333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'bx3tjlk5': {
			'id': 'bx3tjlk5',
			'id_user': 'Акуна Матата /1, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Акуна Матата /1, 7, 8/',
			'category': 'zt5zv3xr',
			'description': '/дом. сос, кашкавал, шунка, луканка, кис. краставички/',
			'price': 9.9916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'kraj07aq': {
			'id': 'kraj07aq',
			'id_user': 'Чикен  /1, 6, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Чикен  /1, 6, 7, 8/',
			'category': 'zt5zv3xr',
			'description': '/сметана, пуш. пиле, сирене, пуш. сирене, яйце, кашкавал/',
			'price': 9.9916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'6dc2v4rd': {
			'id': '6dc2v4rd',
			'id_user': 'Мафиозо  /1, 6, 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Мафиозо  /1, 6, 7/',
			'category': 'zt5zv3xr',
			'description': '/дом. сос, пуш. пиле, пуш. сирене, люти чушки, кашкавал, царевица/',
			'price': 9.9916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'zqtgqzqk': {
			'id': 'zqtgqzqk',
			'id_user': 'Бос  /1, 5, 6, 7, 12/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Бос  /1, 5, 6, 7, 12/',
			'category': 'zt5zv3xr',
			'description': '/дом. сос, шунка, луканка, прясна чушка, яйце, кашкавал/',
			'price': 9.9916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'de3mlfcg': {
			'id': 'de3mlfcg',
			'id_user': 'Ромул  /1, 6, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Ромул  /1, 6, 7, 8/',
			'category': 'zt5zv3xr',
			'description': '/дом. сос, кашкавал, пуш. пиле, пуш. сирене, яйце, царевица, кис. краставички/',
			'price': 9.9916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'do6r0s07': {
			'id': 'do6r0s07',
			'id_user': 'Фата - затворена /1, 6, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Фата - затворена /1, 6, 7, 8/',
			'category': 'zt5zv3xr',
			'description': '/дом. сос, кашкавал, шунка, луканка, сирене, пуш. сирене, гъби, кис. краставички, чеснов сос/',
			'price': 9.9916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'5fm59haf': {
			'id': '5fm59haf',
			'id_user': 'Верди /1, 6, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Верди /1, 6, 7, 8/',
			'category': 'zt5zv3xr',
			'description': '/дом. сос, кашкавал, шунка, гъби, пуш. св. бут, яйце, прес. домати, магданоз/',
			'price': 9.9916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'lgii052q': {
			'id': 'lgii052q',
			'id_user': 'Роси  /1, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Роси  /1, 7, 8/',
			'category': 'zt5zv3xr',
			'description': '/дом. сос, кашкавал, пуш. пиле, пуш. сирене, луканка, сирене, маслини/',
			'price': 10.825,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'plbackav': {
			'id': 'plbackav',
			'id_user': 'Тиси  /1, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Тиси  /1, 7, 8/',
			'category': 'zt5zv3xr',
			'description': '/сметана, кашкавал, шунка, сирене, топ. сирене, прес. чушки/',
			'price': 9.9916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'pxnw7irt': {
			'id': 'pxnw7irt',
			'id_user': 'Маргарита - /1, 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Маргарита - /1, 7/',
			'category': '1ugx5r3b',
			'description': '/дом. сос, моцарела, босилек/',
			'price': 7.6583333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'kmqr1wkw': {
			'id': 'kmqr1wkw',
			'id_user': 'Фокача Фърчита /1, 6, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Фокача Фърчита /1, 6, 7, 8/',
			'category': '1ugx5r3b',
			'description': '/моцарела, итал. Кото, пресен домат, маруля, майонеза, масло/',
			'price': 11.9916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'aqtf2wxy': {
			'id': 'aqtf2wxy',
			'id_user': 'Прошуто Крудо  /1, 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Прошуто Крудо  /1, 7/',
			'category': '1ugx5r3b',
			'description': '/дом. сос, моцарела, итал. Крудо, чери домати, рукола/',
			'price': 11.9916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'ksvxbicx': {
			'id': 'ksvxbicx',
			'id_user': 'Прошуто е Фунги /1, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Прошуто е Фунги /1, 7, 8/',
			'category': '1ugx5r3b',
			'description': '/дом. сос, моцарела, итал. Кото, манатарки/',
			'price': 12.825,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'g00hvjhf': {
			'id': 'g00hvjhf',
			'id_user': 'Саламе Пиканте /1, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Саламе Пиканте /1, 7, 8/',
			'category': '1ugx5r3b',
			'description': '/дом. сос, моцарела, итал. лют салам/',
			'price': 11.6583333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'eqw3pne5': {
			'id': 'eqw3pne5',
			'id_user': 'Куатро Формаджи  /1, 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Куатро Формаджи  /1, 7/',
			'category': '1ugx5r3b',
			'description': '/масло, чери, моцарела, сирне „Ементал”, синьо сирене, чедър/',
			'price': 11.6583333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'akneyn8s': {
			'id': 'akneyn8s',
			'id_user': 'Прошуто и Артишок  /1, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Прошуто и Артишок  /1, 7, 8/',
			'category': '1ugx5r3b',
			'description': '/дом. сос, итал. Кото, моцарела, артишок, риган/',
			'price': 11.9916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'0ocemuh1': {
			'id': '0ocemuh1',
			'id_user': 'Селсиче и Чипола /1, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Селсиче и Чипола /1, 7, 8/',
			'category': '1ugx5r3b',
			'description': '/дом. сос, моцарела, итал. Селсиче, червен лук/',
			'price': 11.6583333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'rl7pbkgv': {
			'id': 'rl7pbkgv',
			'id_user': 'Болонезе /1, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Болонезе /1, 7, 8/',
			'category': 'tyemt4a8',
			'description': '/кайма, лук, дом. сос, босилек, кашкавал/ ..... 450 гр.',
			'price': 7.9083333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.45
		},
		'kvqirm9m': {
			'id': 'kvqirm9m',
			'id_user': 'Миланезе /1, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Миланезе /1, 7, 8/',
			'category': 'tyemt4a8',
			'description': '/шунка, гъби, кашкавал, заквасена сметана, подправки, магданоз/ ..... 450 гр.',
			'price': 7.9083333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.45
		},
		'6knpmkn2': {
			'id': '6knpmkn2',
			'id_user': 'Кали /1, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Кали /1, 7, 8/',
			'category': 'tyemt4a8',
			'description': '/пушено пиле, гъби, заквасена сметана, лук, кашкавал, подправки/ ..... 450 гр.',
			'price': 7.9083333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.45
		},
		'5yl5qcgk': {
			'id': '5yl5qcgk',
			'id_user': 'Фамозо /1, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Фамозо /1, 7, 8/',
			'category': 'tyemt4a8',
			'description': '/пуш. пиле, кис. краставички, кашкавал, заквасена сметана, подправки/',
			'price': 7.9083333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.45
		},
		'ppkjkw76': {
			'id': 'ppkjkw76',
			'id_user': 'Дитреви /1, 4, 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Дитреви /1, 4, 7/',
			'category': 'tyemt4a8',
			'description': '/спанак, сметана, сирене, бадем, кашкавал, подправки, чесън/  ..... 450 гр.',
			'price': 7.9083333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.45
		},
		'wazvde37': {
			'id': 'wazvde37',
			'id_user': 'Мати /1, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Мати /1, 7, 8/',
			'category': 'tyemt4a8',
			'description': '/пил. месо, броколи, заквасена сметана, пармезан, подправки/',
			'price': 7.9083333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.45
		},
		'orf8gll7': {
			'id': 'orf8gll7',
			'id_user': 'Бианко /1, 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Бианко /1, 7/',
			'category': 'tyemt4a8',
			'description': '/ементал, чедър, пекорино, сметана, пармезан, чер. пипер/ ..... 450 гр.',
			'price': 8.7416667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.45
		},
		'tpyrefbd': {
			'id': 'tpyrefbd',
			'id_user': 'Ета /1, 7, 9/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Ета /1, 7, 9/',
			'category': 'npxl7ueb',
			'description': '/шунка, гъби, бешамелов сос, кашкавал, чесън/ ..... 400 гр.',
			'price': 7.4916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.4
		},
		'ewr8smxw': {
			'id': 'ewr8smxw',
			'id_user': 'Мона /1, 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Мона /1, 7/',
			'category': 'npxl7ueb',
			'description': '/спанак, сирене, доматен сос, кашкавал, Бешамелов сос/ ..... 400 гр.',
			'price': 7.4916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.4
		},
		'n6c9ypcv': {
			'id': 'n6c9ypcv',
			'id_user': 'Млечен /6, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Млечен /6, 7, 8/',
			'category': 'ojd11db8',
			'description': '/мляко, чесън, копър, майонеза/ ..... 50 г',
			'price': 1.2416667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'6hcuw6x7': {
			'id': '6hcuw6x7',
			'id_user': 'Майонеза /6, 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Майонеза /6, 7/',
			'category': 'ojd11db8',
			'description': '50 г',
			'price': 1.2416667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'z53k16st': {
			'id': 'z53k16st',
			'id_user': 'Чили сос /1/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Чили сос /1/',
			'category': 'ojd11db8',
			'description': '50 г',
			'price': 1.4916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'73sihzmw': {
			'id': '73sihzmw',
			'id_user': 'Зехтин',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Зехтин',
			'category': 'ojd11db8',
			'description': '40 мл.',
			'price': 1.2416667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'p6mrh91s': {
			'id': 'p6mrh91s',
			'id_user': 'Соев сос',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Соев сос',
			'category': 'ojd11db8',
			'description': '40 мл.',
			'price': 1.2416667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'8yl08kei': {
			'id': '8yl08kei',
			'id_user': 'Балсамов оцет',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Балсамов оцет',
			'category': 'ojd11db8',
			'description': '40 мл.',
			'price': 1.2416667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'm52w9q7g': {
			'id': 'm52w9q7g',
			'id_user': 'Кетчуп /1/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Кетчуп /1/',
			'category': 'ojd11db8',
			'description': '50 г',
			'price': 1.2416667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'ej2uxtd7': {
			'id': 'ej2uxtd7',
			'id_user': 'Сос барбекю /1/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Сос барбекю /1/',
			'category': 'ojd11db8',
			'description': '50 г',
			'price': 1.4916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'p9wbxpmy': {
			'id': 'p9wbxpmy',
			'id_user': 'Чеснова питка /1/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Чеснова питка /1/',
			'category': '3ac2lrlm',
			'description': '',
			'price': 1.6583333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'z5cx66ve': {
			'id': 'z5cx66ve',
			'id_user': 'Сицилианска питка /1, 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Сицилианска питка /1, 7/',
			'category': '3ac2lrlm',
			'description': '',
			'price': 1.6583333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'ke5sfpzg': {
			'id': 'ke5sfpzg',
			'id_user': 'Питка с кашкавал - 1 бр.',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Питка с кашкавал - 1 бр.',
			'category': '3ac2lrlm',
			'description': '',
			'price': 2.9083333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'ecsze5vn': {
			'id': 'ecsze5vn',
			'id_user': 'Питка с кашкавал и чесън - 1 бр.',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Питка с кашкавал и чесън - 1 бр.',
			'category': '3ac2lrlm',
			'description': '',
			'price': 2.9083333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'yg5nw195': {
			'id': 'yg5nw195',
			'id_user': 'Питка с кашкавал и сирене - 1 бр.',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Питка с кашкавал и сирене - 1 бр.',
			'category': '3ac2lrlm',
			'description': '',
			'price': 3.075,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'agxkwmkt': {
			'id': 'agxkwmkt',
			'id_user': 'Царевица',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Царевица',
			'category': 'exh6ls60',
			'description': '',
			'price': 0.4166667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'apzq17ii': {
			'id': 'apzq17ii',
			'id_user': 'Чушки',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Чушки',
			'category': 'exh6ls60',
			'description': '',
			'price': 0.4166667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'4zy9zlml': {
			'id': '4zy9zlml',
			'id_user': 'Кисели краставички',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Кисели краставички',
			'category': 'exh6ls60',
			'description': '',
			'price': 0.4166667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'tbr0235l': {
			'id': 'tbr0235l',
			'id_user': 'Гъби',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Гъби',
			'category': 'exh6ls60',
			'description': '',
			'price': 0.5833333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'nuhxt2eg': {
			'id': 'nuhxt2eg',
			'id_user': 'Маслини',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Маслини',
			'category': 'exh6ls60',
			'description': '',
			'price': 0.5833333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'rrn3iis1': {
			'id': 'rrn3iis1',
			'id_user': 'Сирене',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Сирене',
			'category': 'exh6ls60',
			'description': '',
			'price': 0.5833333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'0d1qmfac': {
			'id': '0d1qmfac',
			'id_user': 'Шунка',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Шунка',
			'category': 'exh6ls60',
			'description': '',
			'price': 0.5833333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'3pmtx74h': {
			'id': '3pmtx74h',
			'id_user': 'Броколи -',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Броколи -',
			'category': 'exh6ls60',
			'description': '',
			'price': 0.5833333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'qhfyaxdc': {
			'id': 'qhfyaxdc',
			'id_user': 'Пушено пиле',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Пушено пиле',
			'category': 'exh6ls60',
			'description': '',
			'price': 1,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'klu39x6a': {
			'id': 'klu39x6a',
			'id_user': 'Свински бут',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Свински бут',
			'category': 'exh6ls60',
			'description': '',
			'price': 1,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'ipzo2fz8': {
			'id': 'ipzo2fz8',
			'id_user': 'Кашкавал',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Кашкавал',
			'category': 'exh6ls60',
			'description': '',
			'price': 1,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'k4t4gkij': {
			'id': 'k4t4gkij',
			'id_user': 'Топено сирене',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Топено сирене',
			'category': 'exh6ls60',
			'description': '',
			'price': 1,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'm5d03tq3': {
			'id': 'm5d03tq3',
			'id_user': 'Синьо сирене',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Синьо сирене',
			'category': 'exh6ls60',
			'description': '',
			'price': 1.5,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'0o50k736': {
			'id': '0o50k736',
			'id_user': 'Италианска шунка',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Италианска шунка',
			'category': 'exh6ls60',
			'description': '',
			'price': 1.5,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'jbb77gfa': {
			'id': 'jbb77gfa',
			'id_user': 'Моцарела - 125 гр.',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Моцарела - 125 гр.',
			'category': 'exh6ls60',
			'description': '',
			'price': 2.6583333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'i7e648w0': {
			'id': 'i7e648w0',
			'id_user': 'Прошуто - 100 гр.',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Прошуто - 100 гр.',
			'category': 'exh6ls60',
			'description': '',
			'price': 3.4916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'1qwwxdu6': {
			'id': '1qwwxdu6',
			'id_user': 'Капрезе с бурата /7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Капрезе с бурата /7/',
			'category': '91vhzmwe',
			'description': '/домати, зехтин, босилек, бурата/ ..... 440 гр.',
			'price': 9.9916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.44
		},
		'l8uriymt': {
			'id': 'l8uriymt',
			'id_user': 'Токи /4, 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Токи /4, 7/',
			'category': '91vhzmwe',
			'description': '/рукола, чери домати, бурата, авокадо, кедрови ядки, балсамова редукция/ ... 350 гр.',
			'price': 11.6583333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.35
		},
		'envet60o': {
			'id': 'envet60o',
			'id_user': 'Френска пица /1, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Френска пица /1, 7, 8/',
			'category': '1ugx5r3b',
			'description': '/дом. сос, моцарела, спанак, сушени домати, сладко от зелени смокини, френско козе сирене/',
			'price': 11.6583333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'jpsh1irr': {
			'id': 'jpsh1irr',
			'id_user': 'Бурата /1, 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Бурата /1, 7/',
			'category': '1ugx5r3b',
			'description': '/дом. сос, моцарела, Бурата, прошуто крудо, чери домати/',
			'price': 14.1583333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'8dxi6fax': {
			'id': '8dxi6fax',
			'id_user': 'Пица Бургер /1, 7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Пица Бургер /1, 7, 8/',
			'category': '1ugx5r3b',
			'description': '/сос барбекю, моцарела, чедър, селсиче, чушки Халапеньо/',
			'price': 11.6583333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'r5k4ph5j': {
			'id': 'r5k4ph5j',
			'id_user': 'Паста Карбонара по оригинална рецепта /1, 6, 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Паста Карбонара по оригинална рецепта /1, 6, 7/',
			'category': 'tyemt4a8',
			'description': '/паста, панчета, айца, пекорино, чесън, чер пипер/ ..... 300 гр.',
			'price': 8.325,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.3
		},
		'b7p7gkcn': {
			'id': 'b7p7gkcn',
			'id_user': 'Ризото с пиле /7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Ризото с пиле /7, 8/',
			'category': 'yczqmbtk',
			'description': '/зеленчуци и сметана, подправки, балсамова редукция/ .......... 350 гр.',
			'price': 7.9083333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.35
		},
		's7o2kn9s': {
			'id': 's7o2kn9s',
			'id_user': 'Ризото с манатарки /7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Ризото с манатарки /7, 8/',
			'category': 'yczqmbtk',
			'description': '/чесън, подправки/ ............ 350 гр.',
			'price': 8.325,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.35
		},
		'2i3bpnps': {
			'id': '2i3bpnps',
			'id_user': 'Халуми /4. 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Халуми /4. 7/',
			'category': 'zh8ts3th',
			'description': 'Запечено сирене Халуми, смокиня, орехи ..... 200 гр.',
			'price': 6.6583333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.2
		},
		'qdoank61': {
			'id': 'qdoank61',
			'id_user': 'Гризини с разядка /1, 6, 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Гризини с разядка /1, 6, 7/',
			'category': 'zh8ts3th',
			'description': 'Гризини, сос: сирене, печени чушки, чесън и подправки',
			'price': 5.325,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'9uoduglj': {
			'id': '9uoduglj',
			'id_user': 'Пармезан /настърган/7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Пармезан /настърган/7/',
			'category': 'ojd11db8',
			'description': '15 г',
			'price': 1.2416667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0
		},
		'a32wdtry': {
			'id': 'a32wdtry',
			'id_user': 'Сладък картоф Батат със сос',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Сладък картоф Батат със сос',
			'category': 'po6sws6r',
			'description': '300 гр.',
			'price': 6.6583333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.3
		},
		'ctiq7d0f': {
			'id': 'ctiq7d0f',
			'id_user': 'Свинско с Халапеньо',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Свинско с Халапеньо',
			'category': 'zucwh6z4',
			'description': '350 гр.',
			'price': 8.325,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.35
		},
		'2p8zc74i': {
			'id': '2p8zc74i',
			'id_user': 'Бейби салата /7, 8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Бейби салата /7, 8/',
			'category': '91vhzmwe',
			'description': '/авокадо, чери домати, бейби моцарела, песто, балсамова редукция/ ..... 300 гр.',
			'price': 11.6583333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.3
		},
		'xd4b6ksc': {
			'id': 'xd4b6ksc',
			'id_user': 'Пушени свински ребърца /8/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Пушени свински ребърца /8/',
			'category': 'zucwh6z4',
			'description': 'Мариновани ...... 500 гр.',
			'price': 9.9916667,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.5
		},
		'vmkyo4wl': {
			'id': 'vmkyo4wl',
			'id_user': 'Бурата /1, 4, 7/',
			'digital_delivery': false,
			'physical_delivery': true,
			'name': 'Бурата /1, 4, 7/',
			'category': 'tyemt4a8',
			'description': '/кедрови ядки, чери домати, сос Песто, Бурата/ ....... 350 гр.',
			'price': 11.6583333,
			'staticAvailValue': 'available',
			'availabilityType': 'fixed',
			'offlineAvailableItems': 0,
			'images': [],
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'weight': 0.35
		}
	},

	// Shipping Data
	'shippings': {
		'j48dn4la': {
			'id': 'j48dn4la',
			'name': 'Поща',
			'description': 'Стоките ще бъдат доставени до 3-5 дни.',
			'vat': 0.2,
			'type': 'FIXED',
			'price': 4.1666667,
			'email': 'Доставка на Поща.<br />Стоките ще бъдат доставени до 3-5 дни.'
		},
		'hdj47dut': {
			'id': 'hdj47dut',
			'name': 'Експресна доставка',
			'description': 'Стоките ще бъдат доставени до 1-2 дни.',
			'vat': 0.2,
			'type': 'FIXED',
			'price': 8.3333333,
			'email': 'Доставка на Експресна доставка.<br />Стоките ще бъдат доставени до 1-2 дни.'
		}
	},

	// Payment Data
	'payments': {
		'8dkejfu5': {
			'id': '8dkejfu5',
			'name': 'Банков превод',
			'description': 'Отложено плащане с банков превод.',
			'email': 'Необходими данни за осъществяване на банково плащане:<br /><br />XXX YYY ZZZ<br /><br />Моля, обърнете внимание, че след като бъде извършено плащането е необходимо да изпратите копие от платежното нареждане заедно с номера на поръчката.',
			'vattype': 'included', // included|excluded|none
			'vat': 0.2,
			'pricetype': 'fixed',
			'price': 0
		}
	},

	// User's data form and agreement text
	'form': {
		'agreement': 'С изпращането на тази Поръчка, Вие се съгласявате с условия на лицензното споразумение, Декларацията за поверителност, както и правото на отказ като потребител. Вашата поръчка ще бъде запазена и &nbsp;обработена само след щракване върху бутона по-долу.',
		'acceptAgreement': false,
		'fields': [
			{
				'id': 'Name',
				'uuid': 'Name',
				'name': 'Име',
				'value': '',
				'type': 'Text',
				'mandatory': true,
				'filter': 'mandatory',
				'shipping': true,
				'custom': false,
				'isVisible': function (prefix) { return true;}
			},
			{
				'id': 'LastName',
				'uuid': 'LastName',
				'name': 'Фамилия',
				'value': '',
				'type': 'Text',
				'mandatory': true,
				'filter': 'mandatory',
				'shipping': true,
				'custom': false,
				'isVisible': function (prefix) { return true;}
			},
			{
				'id': 'Address1',
				'uuid': 'Address1',
				'name': 'Адрес',
				'value': '',
				'type': 'Text',
				'mandatory': true,
				'filter': 'mandatory',
				'shipping': true,
				'custom': false,
				'isVisible': function (prefix) { return true;}
			},
			{
				'id': 'ZipPostalCode',
				'uuid': 'ZipPostalCode',
				'name': 'Пощенски код',
				'value': '',
				'type': 'Text',
				'mandatory': true,
				'filter': 'mandatory',
				'shipping': true,
				'custom': false,
				'isVisible': function (prefix) { return true;}
			},
			{
				'id': 'City',
				'uuid': 'City',
				'name': 'Град',
				'value': '',
				'type': 'Text',
				'mandatory': true,
				'filter': 'mandatory',
				'shipping': true,
				'custom': false,
				'isVisible': function (prefix) { return true;}
			},
			{
				'id': 'StateRegion',
				'uuid': 'StateRegion',
				'name': 'Област',
				'value': '',
				'type': 'Text',
				'mandatory': true,
				'filter': 'mandatory',
				'shipping': true,
				'custom': false,
				'isVisible': function (prefix) { return $('#' + prefix + 'Country').val() != 'us' && $('#' + prefix + 'Country').val() != 'br' && $('#' + prefix + 'Country').val() != 'US' && $('#' + prefix + 'Country').val() != 'BR';}
			}			,{
				'id': 'StateRegion',
				'uuid': 'StateRegion-us',
				'name': 'Област',
				'value': [{"value": "AL","text": "Alabama"},{"value": "AK","text": "Alaska"},{"value": "AZ","text": "Arizona"},{"value": "AR","text": "Arkansas"},{"value": "CA","text": "California"},{"value": "CO","text": "Colorado"},{"value": "CT","text": "Connecticut"},{"value": "DE","text": "Delaware"},{"value": "DC","text": "District of Columbia"},{"value": "FL","text": "Florida"},{"value": "GA","text": "Georgia"},{"value": "HI","text": "Hawaii"},{"value": "ID","text": "Idaho"},{"value": "IL","text": "Illinois"},{"value": "IN","text": "Indiana"},{"value": "IA","text": "Iowa"},{"value": "KS","text": "Kansas"},{"value": "KY","text": "Kentucky"},{"value": "LA","text": "Louisiana"},{"value": "ME","text": "Maine"},{"value": "MD","text": "Maryland"},{"value": "MA","text": "Massachusetts"},{"value": "MI","text": "Michigan"},{"value": "MN","text": "Minnesota"},{"value": "MS","text": "Mississippi"},{"value": "MO","text": "Missouri"},{"value": "MT","text": "Montana"},{"value": "NE","text": "Nebraska"},{"value": "NV","text": "Nevada"},{"value": "NH","text": "New Hampshire"},{"value": "NJ","text": "New Jersey"},{"value": "NM","text": "New Mexico"},{"value": "NY","text": "New York"},{"value": "NC","text": "North Carolina"},{"value": "ND","text": "North Dakota"},{"value": "OH","text": "Ohio"},{"value": "OK","text": "Oklahoma"},{"value": "OR","text": "Oregon"},{"value": "PA","text": "Pennsylvania"},{"value": "RI","text": "Rhode Island"},{"value": "SC","text": "South Carolina"},{"value": "SD","text": "South Dakota"},{"value": "TN","text": "Tennessee"},{"value": "TX","text": "Texas"},{"value": "UT","text": "Utah"},{"value": "VT","text": "Vermont"},{"value": "VA","text": "Virginia"},{"value": "WA","text": "Washington"},{"value": "WV","text": "West Virginia"},{"value": "WI","text": "Wisconsin"},{"value": "WY","text": "Wyoming"}],
				'type': 'DropDownList',
				'mandatory': true,
				'filter': 'mandatory',
				'shipping': true,
				'custom': false,
				'isVisible': function (prefix) { return $('#' + prefix + 'Country').val() == 'US' || $('#' + prefix + 'Country').val() == 'us'; }
			},			{
				'id': 'StateRegion',
				'uuid': 'StateRegion-br',
				'name': 'Област',
				'value': [{"value": "AC","text": "Acre"},{"value": "AL","text": "Alagoas"},{"value": "AP","text": "Amapá"},{"value": "AM","text": "Amazonas"},{"value": "BA","text": "Bahia"},{"value": "CE","text": "Ceará"},{"value": "DF","text": "Distrito Federal"},{"value": "ES","text": "Espírito Santo"},{"value": "GO","text": "Goiás"},{"value": "MA","text": "Maranhão"},{"value": "MT","text": "Mato Grasso"},{"value": "MS","text": "Mato Grosso do Sul"},{"value": "MG","text": "Minas Gerais"},{"value": "PR","text": "Paraná"},{"value": "PB","text": "Paraíba"},{"value": "PA","text": "Pará"},{"value": "PE","text": "Pernambuco"},{"value": "PI","text": "Piauí"},{"value": "RN","text": "Rio Grande do Norte"},{"value": "RS","text": "Rio Grande do Sul"},{"value": "RJ","text": "Rio de Janeiro"},{"value": "RO","text": "Rondônia"},{"value": "RR","text": "Roraima"},{"value": "SC","text": "Santa Catarina"},{"value": "SE","text": "Sergipe"},{"value": "SP","text": "São Paulo"},{"value": "TO","text": "Tocantins"}],
				'type': 'DropDownList',
				'mandatory': true,
				'filter': 'mandatory',
				'shipping': true,
				'custom': false,
				'isVisible': function (prefix) { return $('#' + prefix + 'Country').val() == 'BR' || $('#' + prefix + 'Country').val() == 'br'; }
			},
			{
				'id': 'Phone',
				'uuid': 'Phone',
				'name': 'Телефон (стационарен)',
				'value': '',
				'type': 'Telephone',
				'mandatory': false,
				'filter': 'valGenTelephone',
				'shipping': true,
				'custom': false,
				'isVisible': function (prefix) { return true;}
			},
			{
				'id': 'Email',
				'uuid': 'Email',
				'name': 'Е-мейл адрес',
				'value': '',
				'type': 'Email',
				'mandatory': true,
				'filter': 'mandatory valEmail',
				'shipping': false,
				'custom': false,
				'isVisible': function (prefix) { return true;}
			},
			{
				'id': 'Note',
				'uuid': 'Note',
				'name': 'Бележка',
				'value': '',
				'type': 'TextArea',
				'mandatory': false,
				'filter': '',
				'shipping': false,
				'custom': true,
				'isVisible': function (prefix) { return true;}
			}
		]
	}
};
x5engine.boot.push('x5engine.cart.manager = new x5engine.cart.ecommerce(x5CartData)');

// End of file x5cart.js